{% set name = "rowan" %}
{% set version = "1.3.2" %}
{% set sha256 = "cda6c44f1a85b16a44bea9eba6c94d4ebb2cc0c75e51f1f70d6410f25929fe11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.21

test:
  requires:
    - python {{ python_min }}
  imports:
    - rowan
    - rowan.mapping
    - rowan.geometry
    - rowan.calculus
    - rowan.interpolate
    - rowan.random

about:
  home: https://github.com/glotzerlab/rowan
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Perform quaternion operations using numpy arrays

  description: |
    rowan performs quaternion operations directly on numpy arrays.
    The package does not require conversion of arrays into a special
    quaternion object, ensuring easy integration into existing code,
    but broadcasting is fully supported natively for all operations to
    ensure that code is performant.
  doc_url: http://rowan.readthedocs.io/
  dev_url: https://github.com/glotzerlab/rowan

extra:
  recipe-maintainers:
    - vyasr
    - joaander
    - bdice
