travis:
  secure:
    BINSTAR_TOKEN: jqOH+pET4zwpMoZKFpu619qEi/gF1Sl7KlGTgebhfzFuD4th1okzzuW+CHrnE9rjBaSIqT5lHJiJbX5PMjrVa7/Pg002xUY7ksiYpdiXlQv/xd5xSjn8Ou0tSJGQ4dKhQ4ZI4lB1AGXN0WRO3PTK0iJaYt/F/ur9UgU/xUu490C0LknQW0jy9BDVTLAMrW+YqwP/0T6hfG5Ue4O7cXA6J7wnWYcB7ZQhG5ru1djnWWlSPOq349AebFE7H2YMSlcTYB5jv8K8NJjwbOEehzoCqAMNJ8+2yu0wFXiDBggnTqIpmy3HFRZ00BA8jWpjUDU/+SXYRUl+iSXuN0knsYKdsHfJJZTZ039r/PywNEL5AUb5ldfZGgwgHCEoWyNk+8naA4CrPEZ2+66RU2iLq9FQ0L/N20FtKOW+R61DxVYF/LB4S1vyX8fmtTkaFjJ0Smp3CramdwBN4ZO1fXW41nQBgyxsOGiawJGxF0EW1E8hu1/vuDFliYrPQWMGwhF7xSksnwxf8rSwM0ZeMcDlNrpFJ+PTJlN26qPnEX7XBIcOLwzLSdCYIEAK99r8IDk+gmjCKI41o6B1lNaImw9f0nP0SiHDj9V/m2acTl33JWDTwxJDIEFkIRbODZt8Miwj131bri8TOvKElpTx5J1ir0SY9PdS+Hc7RZjLz/RwintGiRg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
